### ISSUE TITLE
Sort out our print supplier!

### ISSUE THREAD

**Issue by sarahmonster** [sarahmonster/save-me-the-waltz#2]
Using a proper gold effect would go a long way to making the stationery feel super luxe and pretty! We'll probably want to opt for either a foil, or a printed metallic ink—Pantone makes some. 

Tricky aspects of this will be testing the colour and overall print effect before we print a bunch... sine the overall print quality will make a big difference, it would be great to see a proof before we print a whole lot. (Of course, we can use save-the-date cards as a proof, since they're less vital-to-the-whole shebang, and we will need to take into account budget as well!)

For getting proofs made, a local printer is obviously easier, but budget may mean it makes more sense to go with someone else. Since I can't work with a local printer, I'm going to assign this to you—if there are some local companies that look promising, it might be worth visiting them, and then we can run some proofs this week in order to choose.

**Comment by jennybeans** [comment]
JENNYBEANS WAS ASSIGNED. on it! I think loudmouth is going to be a good choice. they do foil and small runs.

**Comment by sarahmonster** [comment]
Oh, and I can provide you whatever files you need, including separations and files for a proof. I was thinking of potentially using some gold and some white on top of the blue (currently using two shades of blue, ps) but if they're going to print each colour individually I'm okay with just straight-up using blue and gold only. 

Loudmouth look good! I would start by paying them a visit and asking them some questions, and seeing if they have any samples you can look at.

**Comment by sarahmonster** [comment]
Catprint.ca seem to be our best option; closing!
