### ISSUE TITLE
Website!

### ISSUE THREAD

**Issue by sarahmonster** [sarahmonster/save-me-the-waltz#5]
We'll want to build a website that fits with the theme of the cards.

Here's what we've got so far: https://jennyrichard2017.wordpress.com/about/

Any more content we need to put here?
Thoughts on setting it up as a one-pager (with each page as a panel), rather than individual pages?
When should this be ready for?

**Comment by jennybeans** [comment]
I am not fussed about one page vs. individual pages!
It should be good for content. I might actually take out the bridal party info as Richard has literally one person and it'll look really unbalanced.

it probably needs to be ready eary december, as getting the stds proofed & out won't likely happen before then!

**Comment by jennybeans** [comment]
update decided to take out the bridal party info.

**Comment by sarahmonster** [comment]
...why on earth did I make TWO issues for website? Maybe I was drunk?

I am only planning on building ONE website. Closing in favour of #4.
